# Generated by Django 4.0.5 on 2022-06-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('universidad', models.CharField(max_length=40)),
                ('anio_inicio', models.IntegerField()),
                ('titulo', models.CharField(max_length=40)),
                ('finalizado', models.CharField(max_length=2)),
            ],
        ),
    ]
